/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_rationality_thetruth_Weechat */

#ifndef _Included_eu_rationality_thetruth_Weechat
#define _Included_eu_rationality_thetruth_Weechat
#ifdef __cplusplus
extern "C" {
#endif
#undef eu_rationality_thetruth_Weechat_WEECHAT_RC_OK
#define eu_rationality_thetruth_Weechat_WEECHAT_RC_OK 0L
#undef eu_rationality_thetruth_Weechat_WEECHAT_RC_OK_EAT
#define eu_rationality_thetruth_Weechat_WEECHAT_RC_OK_EAT 1L
#undef eu_rationality_thetruth_Weechat_WEECHAT_RC_ERROR
#define eu_rationality_thetruth_Weechat_WEECHAT_RC_ERROR -1L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_READ_OK
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_READ_OK 0L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_READ_MEMORY_ERROR
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_READ_MEMORY_ERROR -1L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_READ_FILE_NOT_FOUND
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_READ_FILE_NOT_FOUND -2L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_WRITE_OK
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_WRITE_OK 0L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_WRITE_ERROR
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_WRITE_ERROR -1L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_WRITE_MEMORY_ERROR
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_WRITE_MEMORY_ERROR -2L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_SET_OK_CHANGED
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_SET_OK_CHANGED 2L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_SET_OK_SAME_VALUE
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_SET_OK_SAME_VALUE 1L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_SET_ERROR
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_SET_ERROR 0L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_SET_OPTION_NOT_FOUND
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_SET_OPTION_NOT_FOUND -1L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_UNSET_OK_NO_RESET
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_UNSET_OK_NO_RESET 0L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_UNSET_OK_RESET
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_UNSET_OK_RESET 1L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_UNSET_OK_REMOVED
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_UNSET_OK_REMOVED 2L
#undef eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_UNSET_ERROR
#define eu_rationality_thetruth_Weechat_WEECHAT_CONFIG_OPTION_UNSET_ERROR -1L
/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    trigger_pending_operations
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_trigger_1pending_1operations
  (JNIEnv *, jclass);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    print
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_print
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    print_prefix
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_print_1prefix
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    print_date_tags
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_print_1date_1tags
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    buffer_new
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_eu_rationality_thetruth_Weechat_buffer_1new
  (JNIEnv *, jclass, jstring);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    buffer_set
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_buffer_1set
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    nicklist_add_nick
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_eu_rationality_thetruth_Weechat_nicklist_1add_1nick
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    nicklist_remove_nick
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_nicklist_1remove_1nick
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    nicklist_remove_all
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_nicklist_1remove_1all
  (JNIEnv *, jclass, jlong);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    nicklist_nick_set
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_nicklist_1nick_1set
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    config_boolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_rationality_thetruth_Weechat_config_1boolean
  (JNIEnv *, jclass, jlong);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    config_color
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_rationality_thetruth_Weechat_config_1color
  (JNIEnv *, jclass, jlong);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    config_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_eu_rationality_thetruth_Weechat_config_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    config_get
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_eu_rationality_thetruth_Weechat_config_1get
  (JNIEnv *, jclass, jstring);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    config_integer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_eu_rationality_thetruth_Weechat_config_1integer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     eu_rationality_thetruth_Weechat
 * Method:    config_new
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_eu_rationality_thetruth_Weechat_config_1new
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
