/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
#undef Main_WEECHAT_RC_OK
#define Main_WEECHAT_RC_OK 0L
#undef Main_WEECHAT_RC_OK_EAT
#define Main_WEECHAT_RC_OK_EAT 1L
#undef Main_WEECHAT_RC_ERROR
#define Main_WEECHAT_RC_ERROR -1L
/*
 * Class:     Main
 * Method:    print
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Main_print
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     Main
 * Method:    print_prefix
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Main_print_1prefix
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     Main
 * Method:    buffer_new
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Main_buffer_1new
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Main
 * Method:    buffer_set
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Main_buffer_1set
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     Main
 * Method:    nicklist_add_nick
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Main_nicklist_1add_1nick
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     Main
 * Method:    nicklist_remove_nick
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_Main_nicklist_1remove_1nick
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Main
 * Method:    nicklist_remove_all
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_nicklist_1remove_1all
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
